name: Deploy functions on push/merge

on:
  push:
    branches:
      - development
    paths:
      - '.firebaserc'
      - '.github/workflows/dev-deploy-functions.yml'
      - 'functions/**'
jobs:
  build:
    name: Publish changes

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1
      - name: Checkout development
        run: git checkout development

      # Install frontend dependencies based on nvmrc
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvmfunctions
        working-directory: functions

      - name: Set Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmfunctions.outputs.NVMRC }}"

      - name: Install functions dependencies
        run: npm i
        working-directory: functions

          
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          # Adding --force since after adding minInstances functions every deploy needs a confirmation
          args: deploy --only=functions --project=development --force
        env:
          GCP_SA_KEY: ${{ secrets.SERVICE_ACCOUNT_DEVELOPMENT }}

      - name: Send push notification
        env:
          MSG_TITLE: "Success: Development POAP QR Kiosk"
          MSG_CONTENT: "functions CI success"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json
        
      - name: Send failure push notification
        if: ${{ failure() }}
        env:
          MSG_TITLE: "Failure: Development POAP QR Kiosk"
          MSG_CONTENT: "functions CI failed"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json
        