name: Deploy frontend on push/merge

on:
  push:
    branches:
      - main
    paths:
      - '*.json'
      - '*.js'
      - 'src/**'
      - 'cypress/**'
      - '.github/workflows/prod-deploy-frontend.yml'

jobs:
  # Build the frontend giles
  build:
    name: Compile frontend

    runs-on: ubuntu-latest

    steps:

      # Environment and dependency setup
      - name: Cloning repository
        uses: actions/checkout@v1
      
      - name: Set up Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Create environment files
        run: |
          echo -e "${{ secrets.DOTENV_PRODUCTION }}" > .env

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v15

      - name: Wait for a few minutes in case functions are deploying
        run: |
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "functions/"; then
            echo "Functions files changed, waiting for 4 minutes"
            sleep 240
          else
            echo "No functions changes, not waiting"  
          fi

      # Run cypress tests with a retry (in case a functions deploy clash caused the fail)
      - name: Run e2e frontend tests
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 30 # this command should never time out
          max_attempts: 2 # A function deploy can never take longer than a CI run, so two is enough
          command: npm run test:ci

      # If CI failed, upload the videos for debugging
      - name: Testing failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos # or path/to/artifact


      # Deployment
      - name: Remove debug token from build
        run: sed -i 's/^REACT_APP_APPCHECK_DEBUG_TOKEN=.*$//g' .env

        
      # Deployment
      - name: Build website files
        env:
          NODE_ENV: production
          CI: false
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,firestore --project=production
        env:
          GCP_SA_KEY: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}

      # Notify Mentor
      - name: Send push notification
        env:
          MSG_TITLE: "Success: Production POAP QR Kiosk"
          MSG_CONTENT: "frontend CI success"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json
        
      - name: Send failure push notification
        if: ${{ failure() }}
        env:
          MSG_TITLE: "Failure: Production POAP QR Kiosk"
          MSG_CONTENT: "frontend CI failed"
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=$MSG_TITLE&message=$MSG_CONTENT&priority=1" https://api.pushover.net/1/messages.json
        